services:
  account:
    build:
      context: .
      dockerfile: ./apps/account/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ./.env.development.docker
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  drawing:
    build:
      context: .
      dockerfile: ./apps/drawing/Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - ./.env.development.docker
    depends_on:
      - account
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  game:
    build:
      context: .
      dockerfile: ./apps/game/Dockerfile
    ports:
      - '3002:3002'
    env_file:
      - ./.env.development.docker
    depends_on:
      - drawing
      - account
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
